Repository woowa-techcamp-2022/web-fleemarket-05, pull requests merged in 2022-08, with the labels that each got.

#2 개발 환경 및 프로젝트 설정
  .gitmessage
  .husky/pre-commit
  .vscode/react.code-snippets
  client/.eslintrc.js
  client/babel.config.js
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.tsx
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.config.js
  lint-staged.config.js
  package.json
  prettier.config.js
  server/.eslintrc.js
  server/nest-cli.json
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/tsconfig.build.json
  server/tsconfig.json
  yarn.lock
Labels: feature, frontend, backend

#7 TypeORM 설정, UserEntity 생성
  .gitignore
  server/package.json
  server/src/app.module.ts
  server/src/common/entities/date.entity.ts
  server/src/common/entities/index.ts
  server/src/common/entities/int-id.entity.ts
  server/src/common/entities/uuid.entity.ts
  server/src/config/env.config.ts
  server/src/config/env.validation.ts
  server/src/config/index.ts
  server/src/main.ts
  server/src/users/entities/index.ts
  server/src/users/entities/user.entity.ts
  server/src/users/enums/index.ts
  server/src/users/enums/provider.enum.ts
  server/src/users/users.module.ts
  yarn.lock
Labels: feature, backend

#12 Swagger 관련 설정 추가
  server/package.json
  server/src/common/entities/date.entity.ts
  server/src/common/entities/int-id.entity.ts
  server/src/common/entities/uuid.entity.ts
  server/src/config/docs.config.ts
  server/src/config/index.ts
  server/src/main.ts
  server/src/users/entities/user.entity.ts
  yarn.lock
Labels: documentation, feature, backend

#13 이메일 사용자 회원가입
  server/package.json
  server/src/common/constants/regex.constant.ts
  server/src/common/entities/date.entity.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/constants/index.ts
  server/src/exceptions/custom.exception.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/exceptions/enums/index.ts
  server/src/exceptions/filters/index.ts
  server/src/exceptions/filters/validation-excption.filter.ts
  server/src/exceptions/index.ts
  server/src/exceptions/response/exception.response.ts
  server/src/exceptions/response/index.ts
  server/src/main.ts
  server/src/users/dtos/create-user.dto.ts
  server/src/users/dtos/index.ts
  server/src/users/entities/user.entity.ts
  server/src/users/enums/index.ts
  server/src/users/enums/provider.enum.ts
  server/src/users/responses/index.ts
  server/src/users/responses/is-available.response.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
  server/src/users/users.service.ts
  yarn.lock
Labels: feature, backend

#16 ServeStatic 관련 설정 추가
  client/.eslintrc.js
  client/webpack.config.js
  server/package.json
  server/src/app.module.ts
  yarn.lock
Labels: feature, backend

#17 styled-component 사용 환경 세팅
  client/babel.config.js
  client/package.json
  client/src/App.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/color.ts
  client/src/styles/index.ts
  client/src/styles/reset.ts
  client/src/styles/theme.ts
  client/src/types/styled.d.ts
  client/webpack.config.js
  package.json
  yarn.lock
Labels: feature, frontend

#18 이메일 사용자 로그인/회원가입/로그아웃 API 구현
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/constants/cookie.constant.ts
  server/src/auth/constants/index.ts
  server/src/auth/decorators/auth-user.decorator.ts
  server/src/auth/decorators/index.ts
  server/src/auth/dtos/index.ts
  server/src/auth/dtos/sign-in.dto.ts
  server/src/auth/guards/auth.guard.ts
  server/src/auth/guards/index.ts
  server/src/auth/interfaces/index.ts
  server/src/auth/interfaces/token-payload.interface.ts
  server/src/config/env.validation.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/exceptions/responses/exception.response.ts
  server/src/exceptions/responses/index.ts
  server/src/main.ts
  server/src/users/entities/user.entity.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
  yarn.lock
Labels: feature, backend

#26 Github 인증 API 구현
  client/src/App.tsx
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/config/env.validation.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/users/entities/user.entity.ts
  server/src/users/users.module.ts
  server/src/users/users.service.ts
Labels: feature, backend

#27 S3 이미지 업로드 API 구현
  server/package.json
  server/src/app.module.ts
  server/src/config/docs.config.ts
  server/src/config/env.validation.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/upload/constants/image-option.constant.ts
  server/src/upload/constants/index.ts
  server/src/upload/decorators/api-image.decorator.ts
  server/src/upload/decorators/api-images.decorator.ts
  server/src/upload/decorators/index.ts
  server/src/upload/pipes/image-validation.pipe.ts
  server/src/upload/pipes/images-validation.pipe.ts
  server/src/upload/pipes/index.ts
  server/src/upload/pipes/validators/file-count.validator.ts
  server/src/upload/pipes/validators/file-type.validator.ts
  server/src/upload/pipes/validators/index.ts
  server/src/upload/pipes/validators/max-file-size.validator.ts
  server/src/upload/responses/index.ts
  server/src/upload/responses/upload-image.response.ts
  server/src/upload/responses/upload-images.response.ts
  server/src/upload/upload.controller.ts
  server/src/upload/upload.module.ts
  server/src/upload/upload.service.ts
  yarn.lock
Labels: feature, backend

#30 판매글(Article) 및 좋아요 기능 추가
  server/src/app.module.ts
  server/src/articles/articles.module.ts
  server/src/articles/controllers/articles.controller.ts
  server/src/articles/controllers/category.controller.ts
  server/src/articles/controllers/index.ts
  server/src/articles/dtos/create-article.dto.ts
  server/src/articles/dtos/get-articles.dto.ts
  server/src/articles/dtos/index.ts
  server/src/articles/dtos/update-article-status.dto.ts
  server/src/articles/dtos/update-article.dto.ts
  server/src/articles/entities/article.entity.ts
  server/src/articles/entities/category.entity.ts
  server/src/articles/entities/index.ts
  server/src/articles/enums/article-status.enum.ts
  server/src/articles/enums/index.ts
  server/src/articles/providers/articles.service.ts
  server/src/articles/providers/category.service.ts
  server/src/articles/providers/index.ts
  server/src/common/dtos/index.ts
  server/src/common/dtos/pagination.dto.ts
  server/src/common/entities/int-id.entity.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/users/entities/user.entity.ts
Labels: feature, backend

#29 사용자 동네 관련 API 구현
  server/src/app.module.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/regions/dtos/create-user-region.dto.ts
  server/src/regions/dtos/delete-user-region.dto.ts
  server/src/regions/dtos/index.ts
  server/src/regions/dtos/search-region.dto.ts
  server/src/regions/dtos/update-user-region.dto.ts
  server/src/regions/entities/index.ts
  server/src/regions/entities/region.entity.ts
  server/src/regions/regions.controller.ts
  server/src/regions/regions.module.ts
  server/src/regions/regions.service.ts
  server/src/regions/responses/index.ts
  server/src/regions/responses/region.responses.ts
  server/src/users/entities/user.entity.ts
  server/src/users/responses/user.respones.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: feature, backend

#35 Github workflow 추가
  .github/workflows/node.js.yml
Labels: deploy

#32 Github 로그인 기능 API 변경
  client/src/App.tsx
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/users/dtos/create-github-user.dto.ts
  server/src/users/entities/user.entity.ts
  server/src/users/enums/index.ts
  server/src/users/enums/provder.enum.ts
  server/src/users/users.service.ts
Labels: feature, backend

#37 판매글 동네 정보 추가
  server/src/articles/articles.module.ts
  server/src/articles/controllers/articles.controller.ts
  server/src/articles/dtos/create-article.dto.ts
  server/src/articles/dtos/get-articles.dto.ts
  server/src/articles/dtos/update-article.dto.ts
  server/src/articles/entities/article.entity.ts
  server/src/articles/providers/articles.service.ts
  server/src/auth/auth.module.ts
  server/src/auth/guards/auth.guard.ts
  server/src/exceptions/constants/error-message.constant.ts
  server/src/exceptions/enums/error-code.enum.ts
  server/src/regions/entities/region.entity.ts
  server/src/regions/regions.module.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
Labels: feature, backend

#40 Exceptions 디렉터리 common 디렉터리로 이동
  server/src/articles/providers/articles.service.ts
  server/src/articles/providers/category.service.ts
  server/src/auth/auth.service.ts
  server/src/auth/guards/auth.guard.ts
  server/src/common/exceptions/constants/error-message.constant.ts
  server/src/common/exceptions/constants/index.ts
  server/src/common/exceptions/custom.exception.ts
  server/src/common/exceptions/enums/error-code.enum.ts
  server/src/common/exceptions/enums/index.ts
  server/src/common/exceptions/filters/index.ts
  server/src/common/exceptions/filters/validation-excption.filter.ts
  server/src/common/exceptions/index.ts
  server/src/common/exceptions/responses/exception.response.ts
  server/src/common/exceptions/responses/index.ts
  server/src/main.ts
  server/src/regions/regions.service.ts
  server/src/upload/decorators/api-image.decorator.ts
  server/src/upload/decorators/api-images.decorator.ts
  server/src/upload/pipes/image-validation.pipe.ts
  server/src/upload/pipes/images-validation.pipe.ts
  server/src/upload/pipes/validators/file-count.validator.ts
  server/src/upload/pipes/validators/file-type.validator.ts
  server/src/upload/pipes/validators/max-file-size.validator.ts
  server/src/upload/responses/upload-images.response.ts
  server/src/upload/upload.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: refactoring

#41 React Router Dom 관련 설정 및 기본 레이아웃 추가
  client/package.json
  client/src/App.tsx
  client/src/constants/url.contant.ts
  client/src/index.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/SignInPage.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/z-index.ts
  client/webpack.config.js
  yarn.lock
Labels: feature, frontend

#46 지역, 카테고리 데이터 삽입
  migration/.eslintrc.js
  migration/package.json
  migration/src/dataSource.ts
  migration/src/init.ts
  migration/tsconfig.json
  package.json
  server/src/common/entities/date.entity.ts
  server/src/common/entities/index.ts
  server/src/common/entities/int-id.entity.ts
  server/src/common/entities/uuid.entity.ts
  server/src/regions/entities/region.entity.ts
  yarn.lock
Labels: feature, backend

#47 Icon 컴포넌트 추가
  client/src/assets/icons/chat-filled.svg
  client/src/assets/icons/chat-outline.svg
  client/src/assets/icons/chevron-left.svg
  client/src/assets/icons/heart-filled.svg
  client/src/assets/icons/heart-outline.svg
  client/src/assets/icons/home-filled.svg
  client/src/assets/icons/home-outline.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/store-filled.svg
  client/src/assets/icons/store-outline.svg
  client/src/assets/icons/user-filled.svg
  client/src/assets/icons/user-outline.svg
  client/src/components/common/Icon/Icon.tsx
  client/src/components/common/Icon/index.ts
  client/src/styles/reset.ts
  client/src/types/assets.d.ts
  client/webpack.config.js
Labels: feature, frontend

#55 리브랜딩 및 다크모드 기능 추가
  client/.eslintrc.js
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.tsx
  client/src/assets/icons/index.ts
  client/src/assets/icons/logo.svg
  client/src/assets/icons/moon.svg
  client/src/assets/icons/sun.svg
  client/src/components/BottomNavigation/BottomNavigation.styled.tsx
  client/src/components/common/ToggleThemeButton/ToggleThemeButton.styled.ts
  client/src/components/common/ToggleThemeButton/ToggleThemeButton.tsx
  client/src/components/common/ToggleThemeButton/index.ts
  client/src/constants/nav-list.constant.ts
  client/src/index.tsx
  client/src/layouts/GetStartedLayout/GetStartedLayout.tsx
  client/src/recoil/atoms/theme.atom.ts
  client/src/recoil/selectors/theme.selector.ts
  client/src/styles/GlobalStyle.ts
  client/src/styles/color.ts
  client/src/styles/theme.ts
  client/src/utils/storage.util.ts
  client/src/utils/theme.util.ts
  yarn.lock
Labels: feature, frontend

#51 Header 컴포넌트 구현
  client/src/assets/icons/chevron-left.svg
  client/src/components/common/Header/Header.styled.ts
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/index.ts
  client/src/hooks/useScrollPosition.ts
Labels: feature, frontend

#61 로그인 페이지 구현
  client/package.json
  client/src/App.tsx
  client/src/assets/icons/github.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/mail.svg
  client/src/components/common/AuthInput/AuthInput.styled.ts
  client/src/components/common/AuthInput/AuthInput.tsx
  client/src/components/common/AuthInput/index.ts
  client/src/components/common/Button/Button.styled.ts
  client/src/components/common/Button/Button.tsx
  client/src/components/form/SignInForm/SignInForm.styled.ts
  client/src/components/form/SignInForm/SignInForm.tsx
  client/src/components/form/SignInForm/index.ts
  client/src/constants/message.constant.ts
  client/src/constants/schema.constant.ts
  client/src/constants/url.constant.ts
  client/src/layouts/AuthLayout/AuthLayout.styled.ts
  client/src/layouts/AuthLayout/AuthLayout.tsx
  client/src/layouts/AuthLayout/index.ts
  client/src/pages/EmailSignInPage.tsx
  client/src/pages/SignInPage.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/reset.ts
  yarn.lock
Labels: feature, frontend

#67 백엔드 HTTP 요청 관련 수정
  package.json
  server/src/auth/auth.service.ts
  server/src/auth/interfaces/github-response.interface.ts
  server/src/auth/interfaces/index.ts
  yarn.lock
Labels: backend, fix

#68 카테고리 요청 기능 구현
  client/src/apis/category.ts
  client/src/components/CategoryList/CategoryList.styled.ts
  client/src/components/CategoryList/CategoryList.tsx
  client/src/components/CategoryList/index.ts
  client/src/components/common/LoadingIndiactor/LoadingIndicator.styled.ts
  client/src/components/common/LoadingIndiactor/LoadingIndicator.tsx
  client/src/components/common/LoadingIndiactor/index.ts
  client/src/hooks/useCategoryValue.ts
  client/src/layouts/CategorySelectLayout/CategorySelectLayout.styled.ts
  client/src/layouts/CategorySelectLayout/CategorySelectLayout.tsx
  client/src/layouts/ErrorLayout/ErrorLayout.styled.ts
  client/src/layouts/ErrorLayout/ErrorLayout.tsx
  client/src/layouts/ErrorLayout/index.ts
  client/src/pages/ErrorPage.tsx
  client/src/recoil/atoms/categories.atom.ts
  client/src/recoil/selectors/categories.selector.ts
  client/src/types/Category.ts
  server/src/users/users.service.ts
Labels: feature, frontend

#65 AWS S3 업로드 관련 수정
  server/src/config/env.validation.ts
  server/src/upload/upload.service.ts
Labels: backend, fix

#70 이메일 로그인 기능 추가
  client/src/App.tsx
  client/src/api/auth.ts
  client/src/api/instance.ts
  client/src/api/user.ts
  client/src/assets/icons/index.ts
  client/src/assets/icons/loading.svg
  client/src/components/boundary/AsyncBoundary/AsyncBoundary.tsx
  client/src/components/boundary/AsyncBoundary/index.ts
  client/src/components/boundary/ErrorBoundary/ErrorBoundary.tsx
  client/src/components/boundary/ErrorBoundary/index.ts
  client/src/components/boundary/PendingFallback/PendingFallback.tsx
  client/src/components/boundary/PendingFallback/index.ts
  client/src/components/boundary/RejectedFallback/RejectedFallback.tsx
  client/src/components/boundary/RejectedFallback/index.ts
  client/src/components/common/Button/Button.styled.ts
  client/src/components/common/Button/Button.tsx
  client/src/components/form/EmailSignInForm/EmailSignInForm.styled.ts
  client/src/components/form/EmailSignInForm/EmailSignInForm.tsx
  client/src/components/form/EmailSignInForm/index.ts
  client/src/components/form/SignInForm/index.ts
  client/src/constants/message.constant.ts
  client/src/constants/schema.constant.ts
  client/src/constants/url.constant.ts
  client/src/hooks/useMutation.ts
  client/src/index.tsx
  client/src/pages/EmailSignInPage.tsx
  client/src/recoil/atoms/user.atom.ts
  client/src/recoil/selectors/user.selector.ts
  client/src/router/LoggedInRoutes.tsx
  client/src/router/NotLoggedInRoutes.tsx
  client/src/router/Router.tsx
  client/src/types/error.ts
  client/src/types/user.ts
  client/src/utils/api.util.ts
Labels: feature, frontend

#73 회원가입 페이지 추가
  client/src/App.tsx
  client/src/api/auth.ts
  client/src/assets/icons/check.svg
  client/src/assets/icons/index.ts
  client/src/components/common/AuthInput/AuthInput.tsx
  client/src/components/form/EmailSignUpForm/EmailSignUpForm.styled.ts
  client/src/components/form/EmailSignUpForm/EmailSignUpForm.tsx
  client/src/components/form/EmailSignUpForm/index.ts
  client/src/constants/message.constant.ts
  client/src/constants/regex.constant.ts
  client/src/constants/schema.constant.ts
  client/src/constants/url.constant.ts
  client/src/hooks/useMutation.ts
  client/src/layouts/EmailSignUpLayout/EmailSignUpLayout.styled.ts
  client/src/layouts/EmailSignUpLayout/EmailSignUpLayout.tsx
  client/src/layouts/EmailSignUpLayout/index.ts
  client/src/pages/EmailSignUpPage.tsx
  client/src/pages/GetStartedPage.tsx
  client/src/pages/MyPage.tsx
  client/src/router/NotLoggedInRoutes.tsx
  server/src/common/constants/regex.constant.ts
Labels: feature, frontend

#75 지역 관련 기능 추가
  client/src/App.tsx
  client/src/apis/region.ts
  client/src/assets/icons/add-circle.svg
  client/src/assets/icons/close-circle-outline.svg
  client/src/assets/icons/close-outline.svg
  client/src/assets/icons/index.ts
  client/src/components/region/SearchInput/SearchInput.styled.ts
  client/src/components/region/SearchInput/SearchInput.tsx
  client/src/components/region/SearchInput/index.ts
  client/src/hooks/useDebounce.ts
  client/src/hooks/useInfinityScroll.ts
  client/src/layouts/RegionSearchLayout/RegionSearchLayout.styled.ts
  client/src/layouts/RegionSearchLayout/RegionSearchLayout.tsx
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.styled.ts
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.tsx
  client/src/pages/RegionSearchPage.tsx
  client/src/pages/RegionSelectPage.tsx
  client/src/recoil/atoms/regionsResults.atom.ts
  client/src/router/NotLoggedInRoutes.tsx
  client/src/types/Region.ts
Labels: feature, frontend

#79 동네 관련 기능 구현
  client/src/App.tsx
  client/src/contexts/ModalContext.tsx
  client/src/hooks/uesRegionValue.ts
  client/src/hooks/useModalContext.ts
  client/src/layouts/RegionSearchLayout/RegionSearchLayout.tsx
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.styled.ts
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/RegionSearchPage.tsx
  client/src/pages/RegionSelectPage.tsx
  client/src/recoil/atoms/region.atom.ts
  client/src/recoil/atoms/regionsResults.atom.ts
  client/src/router/NotSetRegionRoutes.tsx
  client/src/router/Router.tsx
  client/src/utils/storage.util.ts
Labels: feature, frontend

#84 카테고리 관련 기능 구현
  client/src/components/CategoryList/CategoryList.tsx
  client/src/recoil/atoms/categories.atom.ts
  client/src/types/Category.ts
  migration/src/data/categories.txt
  migration/src/data/regions.txt
  migration/src/dataSource.ts
  migration/src/init.ts
  server/src/articles/entities/category.entity.ts
Labels: feature, frontend, backend

#82 판매 글 상세 페이지 기능
  client/package.json
  client/src/api/article.ts
  client/src/assets/icons/chevron-down.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/option.svg
  client/src/components/article/Article/ArticleCarousel/ArticleCarousel.styled.ts
  client/src/components/article/Article/ArticleCarousel/ArticleCarousel.tsx
  client/src/components/article/Article/ArticleCarousel/index.ts
  client/src/components/article/Article/ArticleDescription/ArticleDescription.styled.ts
  client/src/components/article/Article/ArticleDescription/ArticleDescription.tsx
  client/src/components/article/Article/ArticleDescription/index.ts
  client/src/components/article/Article/ArticleFooter/ArticleFooter.styled.ts
  client/src/components/article/Article/ArticleFooter/ArticleFooter.tsx
  client/src/components/article/Article/ArticleFooter/index.ts
  client/src/components/article/Article/ArticleStatusDropdown/ArticleStatusDropdown.styled.ts
  client/src/components/article/Article/ArticleStatusDropdown/ArticleStatusDropdown.tsx
  client/src/components/article/Article/ArticleStatusDropdown/index.ts
  client/src/components/boundary/ArticlePendingFallback/ArticlePendingFallback.styled.ts
  client/src/components/boundary/ArticlePendingFallback/ArticlePendingFallback.tsx
  client/src/components/boundary/ArticlePendingFallback/index.ts
  client/src/components/boundary/ArticleRejectedFallback/ArticleRejectedFallback.tsx
  client/src/components/boundary/ArticleRejectedFallback/index.ts
  client/src/components/common/Dropdown/Dropdown.styled.ts
  client/src/components/common/Dropdown/Dropdown.tsx
  client/src/components/common/Dropdown/index.ts
  client/src/components/common/Header/Header.styled.ts
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Scrollable/Scrollable.tsx
  client/src/components/common/Scrollable/index.ts
  client/src/constants/article-status.constant.ts
  client/src/constants/url.constant.ts
  client/src/hooks/useArticleQuery.ts
  client/src/hooks/useDelayRender.ts
  client/src/hooks/useScrollPosition.ts
  client/src/layouts/ArticleLayout/ArticleLayout.styled.ts
  client/src/layouts/ArticleLayout/ArticleLayout.tsx
  client/src/layouts/ArticleLayout/index.ts
  client/src/pages/ArticlePage.tsx
  client/src/recoil/atoms/article.atom.ts
  client/src/recoil/selectors/article.selector.ts
  client/src/router/LoggedInRoutes.tsx
  client/src/styles/GlobalStyle.ts
  client/src/types/article.ts
  client/src/utils/date.util.ts
  server/src/app.module.ts
  server/src/articles/controllers/articles.controller.ts
  server/src/articles/providers/articles.service.ts
  yarn.lock
Labels: feature, frontend

#86 상품 리스트 페이지 구현
  client/src/apis/articles.ts
  client/src/assets/icons/index.ts
  client/src/assets/icons/menu.svg
  client/src/components/ArticleList/ArticleList.styled.ts
  client/src/components/ArticleList/ArticleList.tsx
  client/src/components/ArticleList/index.ts
  client/src/components/CategoryList/CategoryList.styled.ts
  client/src/components/CategoryList/CategoryList.tsx
  client/src/components/common/ArticleItem/ArticleItem.styled.ts
  client/src/components/common/ArticleItem/ArticleItem.tsx
  client/src/components/common/ArticleItem/index.ts
  client/src/constants/url.constant.ts
  client/src/layouts/HomePageLayout/HomePageLayout.styled.ts
  client/src/layouts/HomePageLayout/HomePageLayout.tsx
  client/src/layouts/HomePageLayout/index.ts
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.tsx
  client/src/pages/HomePage.tsx
  client/src/recoil/selectors/articles.selector.ts
  client/src/types/param.ts
  client/src/utils/api.util.ts
  client/src/utils/region.util.ts
Labels: feature, frontend

#93 내 판매 글 조회 기능 추가 및 내 관심 글 조회 기능 추가
  server/src/articles/controllers/articles.controller.ts
  server/src/articles/providers/articles.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: feature, backend

#94 조회수 관련 기능 수정
  server/src/articles/articles.module.ts
  server/src/articles/entities/article.entity.ts
  server/src/articles/entities/index.ts
  server/src/articles/entities/user-view-article.entity.ts
  server/src/articles/providers/articles.service.ts
  server/src/users/entities/user.entity.ts
Labels: feature, backend

#100 채팅 관련 Entity 추가
  server/src/app.module.ts
  server/src/articles/entities/article.entity.ts
  server/src/chats/chats.controller.ts
  server/src/chats/chats.module.ts
  server/src/chats/chats.service.ts
  server/src/chats/entities/chat.entity.ts
  server/src/chats/entities/index.ts
  server/src/chats/entities/message.entity.ts
  server/src/users/entities/user.entity.ts
Labels: feature, backend

#102 내 판매 글 조회 기능 구현
  client/src/api/user.ts
  client/src/components/common/ArticleItem/ArticleItem.styled.ts
  client/src/components/common/ArticleItem/ArticleItem.tsx
  client/src/constants/url.constant.ts
  client/src/layouts/MyArticleListLayout/MyArticleListLayout.styled.ts
  client/src/layouts/MyArticleListLayout/MyArticleListLayout.tsx
  client/src/layouts/MyArticleListLayout/index.ts
  client/src/pages/ArticleListPage.tsx
  client/src/pages/MyArticleListPage.tsx
  client/src/recoil/selectors/user.selector.ts
  client/src/router/LoggedInRoutes.tsx
Labels: feature, frontend, design

#91 상품 리스트 페이지 기능 개선
  client/src/apis/region.ts
  client/src/components/ArticleList/ArticleList.styled.ts
  client/src/components/ArticleList/ArticleList.tsx
  client/src/components/CategoryList/CategoryList.tsx
  client/src/components/boundary/ArticleListPendingFallback/ArticleListPendingFallback.styled.ts
  client/src/components/boundary/ArticleListPendingFallback/ArticleListPendingFallback.tsx
  client/src/components/boundary/ArticleListPendingFallback/index.ts
  client/src/components/common/ArticleItem/ArticleItem.styled.ts
  client/src/components/common/ArticleItem/ArticleItem.tsx
  client/src/components/common/SideModal/SideModal.tsx
  client/src/hooks/useInfinityScroll.ts
  client/src/layouts/HomePageLayout/HomePageLayout.styled.ts
  client/src/layouts/HomePageLayout/HomePageLayout.tsx
  client/src/layouts/RegionSearchLayout/RegionSearchLayout.styled.ts
  client/src/layouts/RegionSearchLayout/RegionSearchLayout.tsx
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.styled.ts
  client/src/layouts/RegionSelectLayout/RegionSelectLayout.tsx
  client/src/pages/RegionSearchPage.tsx
  client/src/recoil/atoms/region.atom.ts
  client/src/recoil/selectors/articles.selector.ts
  client/src/types/param.ts
  server/src/regions/regions.controller.ts
  server/src/regions/regions.service.ts
Labels: frontend, backend, design

#103 채팅 관련 CRUD 기능 추가
  server/src/articles/articles.module.ts
  server/src/articles/controllers/articles.controller.ts
  server/src/articles/providers/articles.service.ts
  server/src/chats/chats.controller.ts
  server/src/chats/chats.module.ts
  server/src/chats/chats.service.ts
  server/src/chats/dtos/create-chat.dto.ts
  server/src/chats/dtos/index.ts
  server/src/chats/entities/chat.entity.ts
  server/src/chats/entities/message.entity.ts
  server/src/chats/providers/chats.service.ts
  server/src/chats/providers/index.ts
  server/src/chats/providers/messages.service.ts
  server/src/common/exceptions/constants/error-message.constant.ts
  server/src/common/exceptions/enums/error-code.enum.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: feature, backend

#106 내 채팅 목록 페이지 추가
  client/src/api/article.ts
  client/src/api/chat.ts
  client/src/components/article/Article/ArticleDescription/ArticleDescription.tsx
  client/src/components/article/Article/ArticleFooter/ArticleFooter.tsx
  client/src/components/chat/ChatItem/ChatItem.styled.ts
  client/src/components/chat/ChatItem/ChatItem.tsx
  client/src/components/chat/ChatItem/index.ts
  client/src/components/chat/MyChatList/MyChatList.tsx
  client/src/components/chat/MyChatList/index.ts
  client/src/components/common/ArticleItem/ArticleItem.tsx
  client/src/components/common/Header/Header.styled.ts
  client/src/components/common/Header/Header.tsx
  client/src/constants/url.constant.ts
  client/src/layouts/ArticleLayout/ArticleLayout.tsx
  client/src/layouts/MyChatPageLayout/MyChatPageLayout.tsx
  client/src/layouts/MyChatPageLayout/index.ts
  client/src/pages/ChatPage.tsx
  client/src/pages/MyChatPage.tsx
  client/src/pages/MyPage.tsx
  client/src/recoil/selectors/chat.selector.ts
  client/src/router/LoggedInRoutes.tsx
  client/src/types/article.ts
  client/src/types/chat.ts
Labels: feature, frontend

#111 테스트 유저 로그인 버튼 추가
  client/src/components/common/Button/Button.styled.ts
  client/src/pages/GetStartedPage.tsx
  client/src/styles/color.ts
Labels: feature, frontend

#115 README 작성
  README.md
  contents/article.png
  contents/branding.png
  contents/main.png
  contents/on-boarding.png
Labels: documentation

#117 다른 페이지 이동 시 상품 리스트 렌더링 오류 문제 개선
  client/src/apis/article.ts
  client/src/apis/auth.ts
  client/src/apis/chat.ts
  client/src/apis/instance.ts
  client/src/apis/region.ts
  client/src/apis/upload.ts
  client/src/apis/user.ts
  client/src/components/ArticleList/ArticleList.tsx
  client/src/components/article/Article/ArticleFooter/ArticleFooter.tsx
  client/src/components/article/Article/ArticleStatusDropdown/ArticleStatusDropdown.tsx
  client/src/components/common/ArticleItem/ArticleItem.styled.ts
  client/src/components/form/EmailSignInForm/EmailSignInForm.tsx
  client/src/components/form/EmailSignUpForm/EmailSignUpForm.tsx
  client/src/hooks/useArticleQuery.ts
  client/src/hooks/useUploadImages.ts
  client/src/layouts/ArticleLayout/ArticleLayout.tsx
  client/src/layouts/RegionSearchLayout/RegionSearchLayout.tsx
  client/src/pages/EditArticlePage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/WriteArticlePage.tsx
  client/src/recoil/atoms/region.atom.ts
  client/src/recoil/selectors/article.selector.ts
  client/src/recoil/selectors/chat.selector.ts
  client/src/recoil/selectors/user.selector.ts
  client/src/types/article.ts
  client/src/utils/api.util.ts
Labels: frontend, refactoring, fix

#118 번들 사이즈 다이어트
  client/package.json
  client/src/router/Router.tsx
  client/webpack.config.js
  yarn.lock
Labels: feature, frontend

#120 API 경로 관련 에러 수정
  client/src/pages/GetStartedPage.tsx
Labels: fix

#121 Hotfix 0.0.31
  client/src/pages/GetStartedPage.tsx
Labels: fix, release
